Include wbia-utool in build requirements
When running `unix_build.sh` to install this package:

```
Obtaining file:///wbia/wbia-plugin-flukematch
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /virtualenv/env3/bin/python3 /virtualenv/env3/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpg2ryqtyl
       cwd: /wbia/wbia-plugin-flukematch
  Complete output (19 lines):
  ERROR: setup requires utool
  Traceback (most recent call last):
    File "/virtualenv/env3/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/virtualenv/env3/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/virtualenv/env3/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-0az3y57z/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 147, in get_requires_for_build_wheel
      config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-0az3y57z/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 127, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-0az3y57z/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 249, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-0az3y57z/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 8, in <module>
      from utool import util_setup
  ModuleNotFoundError: No module named 'utool'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /virtualenv/env3/bin/python3 /virtualenv/env3/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpg2ryqtyl Check the logs for full command output.
```

`utool` is imported in `setup.py` and it seems that only the packages defined
in `pyproject.toml` are available during installation, so we have to include
`wbia-utool` in `pyproject.toml`.