Fix flake8 errors in wbia_flukematch/networks.py
```
wbia_flukematch/networks.py:3:1: F401 'lasagne.nonlinearities.softmax' imported but unused
wbia_flukematch/networks.py:3:1: F401 'lasagne.nonlinearities.sigmoid' imported but unused
wbia_flukematch/networks.py:4:1: F401 'lasagne.objectives.binary_crossentropy' imported but unused
wbia_flukematch/networks.py:5:1: F401 'lasagne.updates.adam' imported but unused
wbia_flukematch/networks.py:5:1: F401 'lasagne.updates.nesterov_momentum' imported but unused
wbia_flukematch/networks.py:6:1: F401 'lasagne.init.Constant' imported but unused
wbia_flukematch/networks.py:7:1: F401 'lasagne.regularization.l2' imported but unused
wbia_flukematch/networks.py:7:1: F401 'lasagne.regularization.regularize_network_params' imported but unused
wbia_flukematch/networks.py:9:1: F401 'theano' imported but unused
wbia_flukematch/networks.py:21:5: E731 do not assign a lambda expression, use a def
wbia_flukematch/networks.py:96:5: E731 do not assign a lambda expression, use a def
wbia_flukematch/networks.py:183:5: E731 do not assign a lambda expression, use a def
wbia_flukematch/networks.py:267:5: E731 do not assign a lambda expression, use a def
wbia_flukematch/networks.py:366:5: E731 do not assign a lambda expression, use a def
wbia_flukematch/networks.py:563:5: F811 redefinition of unused 'softmax' from line 3
wbia_flukematch/networks.py:668:5: F811 redefinition of unused 'softmax' from line 3
wbia_flukematch/networks.py:753:5: E266 too many leading '#' for block comment
wbia_flukematch/networks.py:768:5: E266 too many leading '#' for block comment
wbia_flukematch/networks.py:788:5: E266 too many leading '#' for block comment
wbia_flukematch/networks.py:904:5: E266 too many leading '#' for block comment
wbia_flukematch/networks.py:919:5: E266 too many leading '#' for block comment
wbia_flukematch/networks.py:939:5: E266 too many leading '#' for block comment
wbia_flukematch/networks.py:962:5: E266 too many leading '#' for block comment
wbia_flukematch/networks.py:1006:5: F841 local variable 'bn1' is assigned to but never used
wbia_flukematch/networks.py:1027:5: F841 local variable 'bn3' is assigned to but never used
wbia_flukematch/networks.py:1048:5: F841 local variable 'bn5' is assigned to but never used
wbia_flukematch/networks.py:1069:5: F841 local variable 'bn7' is assigned to but never used
wbia_flukematch/networks.py:1082:5: E266 too many leading '#' for block comment
wbia_flukematch/networks.py:1098:5: E266 too many leading '#' for block comment
wbia_flukematch/networks.py:1115:5: E266 too many leading '#' for block comment
wbia_flukematch/networks.py:1136:5: E266 too many leading '#' for block comment
wbia_flukematch/networks.py:1198:5: F811 redefinition of unused 'softmax' from line 3
```